-- Strategy V2: position reversal — schema reshape

-- Add LONG to HedgeRole enum
ALTER TYPE "HedgeRole" ADD VALUE IF NOT EXISTS 'LONG';

-- Drop legacy hedge columns from Trader (ignore if already gone)
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "shortEntryPrice";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "shortTpPrice";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "currentHedgeLevel";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgeEntryPrice";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgeTpPrice";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgeStopPrice";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgeOrdersCreated";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgeOrdersTriggered";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgePositionsOpened";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgePositionsClosed";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgeStopLosses";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgeTakeProfits";
ALTER TABLE "Trader" DROP COLUMN IF EXISTS "hedgeRecreations";

-- V2 trader fields
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3);
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "endsAt" TIMESTAMP(3);
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "currentSide" TEXT;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "currentPositionNumber" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "entryPrice" TEXT;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "tpPrice" TEXT;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "slPrice" TEXT;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "quantity" TEXT;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "positionsOpened" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "positionsClosed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "winningPositions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "losingPositions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "takeProfits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "stopLosses" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "longPositions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "shortPositions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "totalFees" TEXT NOT NULL DEFAULT '0';
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "timelineJson" TEXT NOT NULL DEFAULT '[]';

-- Configuration: replace hedge knobs with V2 knobs
ALTER TABLE "Configuration" DROP COLUMN IF EXISTS "hedgeDistance";
ALTER TABLE "Configuration" DROP COLUMN IF EXISTS "hedgeTpPercent";
ALTER TABLE "Configuration" DROP COLUMN IF EXISTS "hedgeSlPercent";
ALTER TABLE "Configuration" DROP COLUMN IF EXISTS "shortTpPercent";

ALTER TABLE "Configuration" ADD COLUMN IF NOT EXISTS "traderLifetimeHours" INTEGER NOT NULL DEFAULT 24;
ALTER TABLE "Configuration" ADD COLUMN IF NOT EXISTS "takeProfitPercent" TEXT NOT NULL DEFAULT '0.10';
ALTER TABLE "Configuration" ADD COLUMN IF NOT EXISTS "stopLossPercent" TEXT NOT NULL DEFAULT '0.10';
ALTER TABLE "Configuration" ADD COLUMN IF NOT EXISTS "startingSide" TEXT NOT NULL DEFAULT 'SHORT';
