const config = {
  mode: process.argv.includes("--live") ? "live" : "test",
  apiKey: process.env.BINANCE_API_KEY || "",
  apiSecret: process.env.BINANCE_API_SECRET || "",
  baseRestUrl: "https://fapi.binance.com",
  baseWsUrl: "wss://fstream.binance.com",
  maxTraders: 3,
  enableTradingWindow: false,
  enableScannerFilters: false,
  feeRate: 0.0004,
  slippageRate: 0.0002,
  riskPerTradeUSDT: 20,
  positionNotionalUSDT: 50,
  equityFraction: 0.10,
  leverage: 10,
  levelCount: 2,
  levelSpacingPercent: 0.2,
  takeProfitPercent: 1,
  stopLossPercent: 3,
  ladderInitialLevels: 10,
  ladderRefillThreshold: 1,
  maxDoubles: 5,
  startingBalanceUSDT: 100,
  scannerIntervalMs: 1 * 60 * 1000,
  minChange: 1,
  maxChange: 8,
  volumeRatio: 0.15,
  minRangePercent: 1.5,
  depthMin: 200000,
  depthMax: 5000000,
  spreadMin: 0.0001,
  spreadMax: 0.002,
  recvWindow: 5000
};

module.exports = config;
