-- Capital step progression

ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "traderAllocatedAmount" TEXT NOT NULL DEFAULT '0';
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "capitalSteps" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "currentStep" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "currentStepAmount" TEXT NOT NULL DEFAULT '0';
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "highestStepReached" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "lowestStepReached" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "stepIncreases" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "stepDecreases" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "step1Trades" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Trader" ADD COLUMN IF NOT EXISTS "maxStepTrades" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Configuration" ADD COLUMN IF NOT EXISTS "capitalSteps" INTEGER NOT NULL DEFAULT 5;
